const names = ["Warping Chiyo", 
"R3AL_fm",
"sadotterz", 
"t4teeth", 
"ryanfrogz", 
"sprunklo", 
"Kurt Munky", 
"MIRA", 
"Install a Billion Little Inchworms", 
"flyman347", 
"toxicsporecore", 
"Renii.Star", 
"BAUM", 
"savoa", 
"Hurricane Fordy", 
"tweemail", 
"jessica may", 
"Common ZenZe", 
"Veronica Violence", 
"Lynxy", 
"Ecrylian", 
"chk!dsk", 
"PLUSTWENTYFOUR", 
"DJ GATOR AIDS", 
"ragdoll physics", 
"verity", 
"Teetow", 
"Popbot", 
"J3N2000", 
"hyperlnxx", 
"[PROTO EDEN]", 
"dynastic",
"ok slime", 
"13moonlanding", 
"Cimilo1273", 
"The Daneyoable", 
"keyesgen", 
"pjpriiincess", 
"Detatchi", 
"eris mirror", 
"Any-Any", 
"SÍODA", 
"DJ Daddy Yonqui", 
"littleflodus", 
"BuzzyBee", 
"Nico", 
"Blaire Bombshell", 
"TheGooseMafia", 
"ELN", 
"dotC0D3 (or .C0D3)", 
"Duna (aka Whitefish)", 
"m3taphysics", 
"Dreamcoat Rising", 
"fuck", 
"pacificship", 
"ryanfrogz", 
"Laura97", 
"slxxpyhxxd", 
"irven", 
"Crash Amen", 
"YARHGANG", 
"Katheriina", 
"Gibusnipu", 
"i.v.", 
"FOAM SWORDS", 
"22oh6", 
"DJ B++", 
"Plasma1073", 
"drow-z", 
"hellomynameisjoe", 
"MixmstrStel", 
"lumaline", 
"nek0baby",
"KITTYPUPPY", 
"P3RC!", 
"mentaly sane girl", 
"Hayden Jason", 
"SHARTCHAN", 
"mila hays",
"mikel romberg", 
"dakist4t", 
"sapphire brew", 
"The Dimmest Bulb", 
"DARYA PLUR", 
"algo", 
"lau", 
"wormhole!!",
"liacore", 
"scoot 🌸", 
"m0u", 
"Malísima", 
"DJ Re:Code", 
"Y2F0", 
"illusori",
"babydactyl", 
"Kenny Riot", 
"kes", 
"Peter Pan (Randy Constan)", 
"guy with dog", 
"guy with estrogen"
]

const shuffled = names
    .map(value => ({ value, sort: Math.random() }))
    .sort((a, b) => a.sort - b.sort)
    .map(({ value }) => value);
    
const links = {
    "R3AL_fm": "https://r3alfm.tumblr.com",
    "sadotterz": "https://www.youtube.com/@sadotterz",
    "t4teeth": "https://teeth.garden",
    "ryanfrogz": "https://www.youtube.com/@ryanfrogz",
    "sprunklo": "https://soundcloud.com/sprunklo",
    "Peter Pan (Randy Constan)": "https://pixyland.org",
    "Kurt Munky": "https://soundcloud.com/iooiooi",
    "MIRA": "https://open.spotify.com/artist/6roWZoFMVFGDL20XYvRgJ1",
    "Install a Billion Little Inchworms": "https://soundcloud.com/install-inchworm",
    "flyman347": "https://x.com/flywoman347",
    "toxicsporecore": "https://bandlab.com/bambeany",
    "Renii.Star": "https://soundcloud.com/reniistar",
    "BAUM": "https://soundcloud.com/musicbaum",
    "savoa": "https://soundcloud.com/savoa",
    "Hurricane Fordy": "https://www.youtube.com/@Hurricane_Fordy",
    "tweemail": "https://tweemail.carrd.co/",
    "jessica may": "https://bsky.app/profile/jess.dyke.city",
    "Common ZenZe": "https://soundcloud.com/commonzenze",
    "Veronica Violence": "https://veronicaviolence.neocities.org/",
    "Lynxy": "https://soundcloud.com/t_k_a",
    "Ecrylian": "https://ecrylian.bandcamp.com",
    "chk!dsk": "http://adamsandler.click",
    "PLUSTWENTYFOUR": "https://instagram.com/plustwentyfour",
    "DJ GATOR AIDS": "https://linktr.ee/gatoraidsmp3",
    "ragdoll physics": "https://nocliprecords.neocities.org/ragdollphysics",
    "Teetow": "https://soundcloud.com/teetow",
    "Popbot": "https://popbot.work/",
    "J3N2000": "https://J3n2000.bandcamp.com",
    "hyperlnxx": "https://hyperlnxx.starsyndicate.xyz/",
    "[PROTO EDEN]": "https://discord.gg/Vbs5ejbTHw",
    "guy with dog": "https://guywith.dog",
    "dynastic": "https://soundcloud.com/dynastic",
    "ok slime": "https://soundcloud.com/ok-slime",
    "13moonlanding": "https://youtube.com/@13moonlanding",
    "Cimilo1273": "https://linktr.ee/cimilo1273",
    "The Daneyoable": "https://soundcloud.com/thedanyoable",
    "keyesgen": "https://keyesgen.com",
    "pjpriiincess": "https://pjpriiincess.bandcamp.com/",
    "Detatchi": "linktr.ee/detatchi",
    "eris mirror": "https://eris-mirror.carrd.co/",
    "Any-Any": "https://spacehey.com/Any_Any",
    "SÍODA": "https://sioda.ie/",
    "DJ Daddy Yonqui": "https://soundcloud.com/daddyyonqui",
    "littleflodus": "https://littleflodus.neocities.org",
    "BuzzyBee": "https://www.youtube.com/@buzzybeemusic7394",
    "Nico": "https://soundcloud.com/nicolaipulley",
    "Blaire Bombshell": "https://linktr.ee/blairebombshell",
    "TheGooseMafia": "www.instagram.com/thegoosemafia",
    "ELN": "https://thecryxaationroom.straw.page/links",
    "dotC0D3 (or .C0D3)": "https://codesito.bandcamp.com/",
    "Duna (aka Whitefish)": "https://flow.page/whitefish",
    "m3taphysics": "https://open.spotify.com/artist/4PPqihCNFUMcL3I8bR6Q6w",
    "Dreamcoat Rising": "https://dreamcoatrising.bandcamp.com/",
    "fuck": "https://mackenziereal.bandcamp.com/",
    "pacificship": "https://soundcloud.com/pacificship-895",
    "Laura97": "https://twitter.com/mem0ry97",
    "slxxpyhxxd": "https://slxxpyhxxd.neocities.org/home",
    "irven": "https://soundcloud.com/irven_777",
    "Crash Amen": "https://soundcloud.com/crashamen",
    "YARHGANG": "https://crimp.world",
    "Katheriina": "https://soundcloud.com/kathscoffeeshop",
    "Gibusnipu": "https://gibusnipu.bandcamp.com/",
    "i.v.": "https://megalowomania.straw.page",
    "FOAM SWORDS": "https://linktr.ee/foamswords",
    "22oh6": "https://soundcloud.com/22oh6",
    "DJ B++": "soundcloud.com/davidcle39",
    "Plasma1073": "https://deadwaxrecs.bandcamp.com/",
    "drow-z": "https://plasma1073.bandcamp.com/",
    "hellomynameisjoe": "https://hellomynameisjoe.pronounmail.com",
    "MixmstrStel": "https://soundcloud.com/mixmstrstel",
    "lumaline": "https://lumalinemusic.com/",
    "nek0baby": "https://soundcloud.com/nek0baby",
    "KITTYPUPPY": "https://soundcloud.com/kittypuppy",
    "P3RC!": "http://p3rcimusic.kittygirl.me/",
    "Hayden Jason": "https://soundcloud.com/hayden-jason",
    "mila hays": "https://www.instagram.com/clearlyhayzz/",
    "mikel romberg": "https://www.instagram.com/lokacannabis/",
    "SHARTCHAN": "https://www.instagram.com/shartchan/",
    "dakist4t": "https://soundcloud.com/thekidstat",
    "sapphire brew": "https://soundcloud.com/liquidisotek",
    "The Dimmest Bulb": "https://linktr.ee/lightfixtured",
    "DARYA PLUR": "https://soundcloud.com/dary4",
    "algo": "https://soundcloud.com/algo-525857984",
    "lau": "https://laulaulau.bandcamp.com/",
    "wormhole!!": "https://linktr.ee/_worm.hole_",
    "liacore": "https://open.spotify.com/artist/5wT2QRHNNeRz3rNSteZ8FR",
    "scoot 🌸": "https://www.youtube.com/@scoot_flower_emoji",
    "m0u": "https://soundcloud.com/dairacoer",
    "Malísima": "",
    "DJ Re:Code": "https://m.soundcloud.com/djrecode",
    "Y2F0": "https://data-log.bandcamp.com/album/reminiscence",
    "illusori": "https://m.soundcloud.com/iliusori",
    "Kenny Riot": "https://soundcloud.com/kenny-riot"
};

module.exports = {
    names,
    shuffled,
    summary: shuffled.slice(0, 10),
    links
}
