CREATE TYPE CAUSE AS ENUM ('pcrf', 'lio');

CREATE TABLE IF NOT EXISTS donation (
    id SERIAL PRIMARY KEY,
    email VARCHAR NOT NULL,
    amount NUMERIC NOT NULL,
    cause CAUSE NOT NULL,
    message VARCHAR,
    done BOOL NOT NULL DEFAULT FALSE,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);